export const actionType = {
  RECEIVE_PRODUCT_LIST: "RECEIVE_PRODUCT_LIST",
  RECEIVE_PRODUCT_BY_ID: "RECEIVE_PRODUCT_BY_ID",
  BUY_PRODUCT: "BUY_PRODUCT",
  REMOVE_PRODUCT: "REMOVE_PRODUCT",
  REMOVE_ALL_PRODUCT:"REMOVE_ALL_PRODUCT"
};
